from __future__ import annotations

from datetime import UTC, datetime
from html import escape
from io import BytesIO
from typing import Any

from fpdf import FPDF
from openpyxl import Workbook
from openpyxl.styles import Font
from openpyxl.utils import get_column_letter

from nexa_bos_api.identity.models import User


def _safe_cell(value: object) -> object:
    if isinstance(value, str) and value.startswith(("=", "+", "-", "@")):
        return f"'{value}"
    return value


def _metadata(payload: dict[str, Any], actor: User) -> list[tuple[str, str]]:
    filters = payload.get("filters") or {}
    active_filters = (
        ", ".join(f"{key}={value}" for key, value in filters.items() if value is not None) or "None"
    )
    return [
        ("Report", str(payload.get("title") or "Asset Report")),
        ("Visibility Scope", str(payload.get("reportingScope") or "None")),
        ("Filters", active_filters),
        ("Rows", str(payload.get("total") or 0)),
        ("Generated By", f"{actor.full_name} ({actor.user_code})"),
        ("Generated At", datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")),
    ]


def _rows(payload: dict[str, Any]) -> list[list[object]]:
    items = payload.get("items") or []
    if not items:
        return [["Result"], ["No rows"]]
    headers = list(items[0].keys())
    return [headers, *[[item.get(key, "") for key in headers] for item in items]]


def build_excel(payload: dict[str, Any], actor: User) -> bytes:
    workbook = Workbook()
    metadata = workbook.active
    metadata.title = "Metadata"
    bold = Font(bold=True)
    for row_index, (label, value) in enumerate(_metadata(payload, actor), start=1):
        metadata.cell(row_index, 1, label).font = bold
        metadata.cell(row_index, 2, _safe_cell(value))
    results = workbook.create_sheet("Asset Report")
    for row_index, row in enumerate(_rows(payload), start=1):
        for column_index, value in enumerate(row, start=1):
            cell = results.cell(row_index, column_index, _safe_cell(value))
            if row_index == 1:
                cell.font = bold
            results.column_dimensions[get_column_letter(column_index)].width = min(
                40, max(12, len(str(value or "")) + 2)
            )
    buffer = BytesIO()
    workbook.save(buffer)
    return buffer.getvalue()


def _pdf_safe(value: object) -> str:
    return str(value).encode("latin-1", "replace").decode("latin-1")


def build_pdf(payload: dict[str, Any], actor: User) -> bytes:
    pdf = FPDF(orientation="L")
    pdf.set_auto_page_break(auto=True, margin=12)
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 8, "NEXA BOS - Asset & Inventory", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", size=8)
    for label, value in _metadata(payload, actor):
        pdf.cell(0, 5, _pdf_safe(f"{label}: {value}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)
    for index, row in enumerate(_rows(payload)):
        pdf.set_font("Helvetica", "B" if index == 0 else "", 7)
        pdf.multi_cell(
            0,
            4,
            _pdf_safe(" | ".join(str(value or "") for value in row)),
            new_x="LMARGIN",
            new_y="NEXT",
        )
    return bytes(pdf.output())


def build_print_html(payload: dict[str, Any], actor: User) -> str:
    metadata = "".join(
        f"<tr><th>{escape(label)}</th><td>{escape(value)}</td></tr>"
        for label, value in _metadata(payload, actor)
    )
    rows = _rows(payload)
    header = "".join(f"<th>{escape(str(value))}</th>" for value in rows[0])
    body = "".join(
        "<tr>" + "".join(f"<td>{escape(str(value or ''))}</td>" for value in row) + "</tr>"
        for row in rows[1:]
    )
    title = escape(str(payload.get("title") or "Asset Report"))
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>{title}</title>
  <style>
    body {{ font-family: Arial, sans-serif; color: #0f172a; margin: 24px; }}
    table {{ border-collapse: collapse; width: 100%; margin-top: 16px; }}
    th, td {{ border: 1px solid #cbd5e1; padding: 6px; font-size: 11px; text-align: left; }}
    th {{ background: #f8fafc; }}
    @media print {{ button {{ display: none; }} }}
  </style>
</head>
<body>
  <button type="button" onclick="window.print()">Print</button>
  <h1>NEXA BOS - {title}</h1>
  <table>{metadata}</table>
  <table><thead><tr>{header}</tr></thead><tbody>{body}</tbody></table>
</body>
</html>
"""
