from __future__ import annotations

from datetime import UTC, datetime
from io import BytesIO
from typing import Any

from fpdf import FPDF
from openpyxl import Workbook
from openpyxl.styles import Font
from openpyxl.utils import get_column_letter

from nexa_bos_api.identity.models import User


def _meta_rows(
    *,
    title: str,
    actor: User,
    period: dict[str, Any] | None,
    reporting_scope: str | None,
    filters: dict[str, Any],
    total: int | None,
) -> list[tuple[str, str]]:
    generated = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    period_label = "-"
    if period:
        period_label = f"{period.get('label', '')} ({period.get('from')} - {period.get('to')})"
    active = ", ".join(f"{key}={value}" for key, value in filters.items() if value) or "None"
    rows = [
        ("Report Title", title),
        ("Generated Date/Time", generated),
        ("Selected Period", period_label),
        ("Active Filters", active),
        ("Reporting Scope", reporting_scope or "None"),
        ("Generated By", f"{actor.full_name} ({actor.user_code})"),
    ]
    if total is not None:
        rows.append(("Rows", str(total)))
    return rows


def _pdf_safe(value: object) -> str:
    return str(value).encode("latin-1", "replace").decode("latin-1")


def build_excel(
    *,
    title: str,
    actor: User,
    payload: dict[str, Any],
    filters: dict[str, Any],
) -> bytes:
    workbook = Workbook()
    meta_sheet = workbook.active
    meta_sheet.title = "Metadata"
    header = Font(bold=True)
    for index, (label, value) in enumerate(
        _meta_rows(
            title=title,
            actor=actor,
            period=payload.get("period") or payload.get("currentPeriod"),
            reporting_scope=payload.get("reportingScope"),
            filters=filters,
            total=payload.get("total"),
        ),
        start=1,
    ):
        meta_sheet.cell(index, 1, label).font = header
        meta_sheet.cell(index, 2, value)
    data_sheet = workbook.create_sheet("Results")
    rows = _tabular_rows(payload)
    for row_index, row in enumerate(rows, start=1):
        for col_index, value in enumerate(row, start=1):
            cell = data_sheet.cell(row_index, col_index, value)
            if row_index == 1:
                cell.font = header
            data_sheet.column_dimensions[get_column_letter(col_index)].width = min(
                40, max(12, len(str(value)) + 2)
            )
    buffer = BytesIO()
    workbook.save(buffer)
    return buffer.getvalue()


def build_pdf(
    *,
    title: str,
    actor: User,
    payload: dict[str, Any],
    filters: dict[str, Any],
) -> bytes:
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=12)
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 8, "NEXA BOS", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, _pdf_safe(title), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", size=9)
    for label, value in _meta_rows(
        title=title,
        actor=actor,
        period=payload.get("period") or payload.get("currentPeriod"),
        reporting_scope=payload.get("reportingScope"),
        filters=filters,
        total=payload.get("total"),
    ):
        pdf.cell(0, 5, _pdf_safe(f"{label}: {value}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    rows = _tabular_rows(payload)
    if rows:
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(
            0,
            5,
            _pdf_safe(" | ".join(str(item) for item in rows[0])),
            new_x="LMARGIN",
            new_y="NEXT",
        )
        pdf.set_font("Helvetica", size=8)
        for row in rows[1:60]:
            pdf.cell(
                0,
                5,
                _pdf_safe(" | ".join(str(item) for item in row)),
                new_x="LMARGIN",
                new_y="NEXT",
            )
        if len(rows) > 61:
            pdf.cell(
                0,
                5,
                f"... {len(rows) - 61} additional rows omitted in PDF",
                new_x="LMARGIN",
                new_y="NEXT",
            )
    return bytes(pdf.output())


def build_print_html(
    *,
    title: str,
    actor: User,
    payload: dict[str, Any],
    filters: dict[str, Any],
) -> str:
    meta = "".join(
        f"<tr><th>{label}</th><td>{value}</td></tr>"
        for label, value in _meta_rows(
            title=title,
            actor=actor,
            period=payload.get("period") or payload.get("currentPeriod"),
            reporting_scope=payload.get("reportingScope"),
            filters=filters,
            total=payload.get("total"),
        )
    )
    rows = _tabular_rows(payload)
    body = ""
    if rows:
        header = "".join(f"<th>{item}</th>" for item in rows[0])
        data = "".join(
            "<tr>" + "".join(f"<td>{item}</td>" for item in row) + "</tr>" for row in rows[1:]
        )
        body = f"<table><thead><tr>{header}</tr></thead><tbody>{data}</tbody></table>"
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>{title}</title>
  <style>
    body {{ font-family: Arial, sans-serif; color: #0f172a; margin: 24px; }}
    h1 {{ font-size: 20px; margin-bottom: 4px; }}
    table {{ border-collapse: collapse; width: 100%; margin-top: 16px; }}
    th, td {{ border: 1px solid #cbd5e1; padding: 6px 8px; font-size: 12px; text-align: left; }}
    th {{ background: #f8fafc; }}
    @media print {{ button {{ display: none; }} }}
  </style>
</head>
<body>
  <button onclick="window.print()">Print</button>
  <h1>NEXA BOS - {title}</h1>
  <table>{meta}</table>
  {body}
</body>
</html>
"""


def _tabular_rows(payload: dict[str, Any]) -> list[list[object]]:
    if payload.get("items"):
        items = payload["items"]
        if items and isinstance(items[0], dict):
            headers = list(items[0].keys())
            return [headers, *[list(item.get(key, "") for key in headers) for item in items]]
    kpis = payload.get("kpis")
    if isinstance(kpis, dict):
        rows: list[list[object]] = [["Metric", "Count", "Value"]]
        for key, value in kpis.items():
            if isinstance(value, dict):
                rows.append([key, value.get("count", ""), value.get("value", "")])
            else:
                rows.append([key, "", value])
        return rows
    rankings = payload.get("rankings")
    if isinstance(rankings, dict) and rankings.get("employees"):
        rows = [["Rank", "Employee", "Value", "Count"]]
        for item in rankings["employees"]:
            rows.append([item.get("rank"), item.get("name"), item.get("value"), item.get("count")])
        return rows
    if payload.get("currentKpis"):
        return [
            ["Metric", "Current", "Previous", "Difference", "% Change"],
            [
                payload.get("metric"),
                payload.get("current"),
                payload.get("previous"),
                payload.get("absoluteDifference"),
                payload.get("percentageChange")
                if payload.get("percentageChange") is not None
                else "n/a",
            ],
        ]
    return [["Result"], ["No rows"]]
